/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Data.DBConnection;
import Models.Client;

/**
 *
 * @author Administrator
 */
public class AddClient extends javax.swing.JFrame {

    /**
     * Creates new form AddClient
     */
    public AddClient() {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(AddProduct.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_annule = new javax.swing.JButton();
        jL_info1 = new javax.swing.JLabel();
        btn_saveClient = new javax.swing.JButton();
        client_name = new javax.swing.JTextField();
        jj = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        client_phone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        client_adress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        client_email = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_annule.setBackground(new java.awt.Color(13, 71, 161));
        btn_annule.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        btn_annule.setForeground(new java.awt.Color(255, 255, 255));
        btn_annule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_cancel_white.png"))); // NOI18N
        btn_annule.setText("Annule");
        btn_annule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_annuleActionPerformed(evt);
            }
        });
        jPanel1.add(btn_annule, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 170, 30));

        jL_info1.setFont(new java.awt.Font("Footlight MT Light", 0, 24)); // NOI18N
        jL_info1.setForeground(new java.awt.Color(0, 76, 246));
        jL_info1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_info1.setText("jLabel7");
        jPanel1.add(jL_info1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 320, 20));

        btn_saveClient.setBackground(new java.awt.Color(13, 71, 161));
        btn_saveClient.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        btn_saveClient.setForeground(new java.awt.Color(255, 255, 255));
        btn_saveClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_save_white.png"))); // NOI18N
        btn_saveClient.setText("Enregistrer");
        btn_saveClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveClientActionPerformed(evt);
            }
        });
        jPanel1.add(btn_saveClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 180, 30));

        client_name.setBackground(new java.awt.Color(144, 202, 255));
        client_name.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        client_name.setForeground(new java.awt.Color(0, 0, 0));
        client_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        client_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client_nameActionPerformed(evt);
            }
        });
        jPanel1.add(client_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 280, 30));

        jj.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jj.setForeground(new java.awt.Color(0, 0, 0));
        jj.setText("Nom complet");
        jPanel1.add(jj, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, 30));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Telephone");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, 30));

        client_phone.setBackground(new java.awt.Color(144, 202, 255));
        client_phone.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        client_phone.setForeground(new java.awt.Color(0, 0, 0));
        client_phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        client_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client_phoneActionPerformed(evt);
            }
        });
        jPanel1.add(client_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 280, 30));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Adresse");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 130, 30));

        client_adress.setBackground(new java.awt.Color(144, 202, 255));
        client_adress.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        client_adress.setForeground(new java.awt.Color(0, 0, 0));
        client_adress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        client_adress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client_adressActionPerformed(evt);
            }
        });
        jPanel1.add(client_adress, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 280, 30));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Email");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 130, 30));

        client_email.setBackground(new java.awt.Color(144, 202, 255));
        client_email.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        client_email.setForeground(new java.awt.Color(0, 0, 0));
        client_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        client_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client_emailActionPerformed(evt);
            }
        });
        jPanel1.add(client_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 280, 30));

        jPanel2.setBackground(new java.awt.Color(41, 98, 255));

        jLabel1.setBackground(new java.awt.Color(41, 98, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ajout d'un nouveau client");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 430, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_annuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_annuleActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_annuleActionPerformed

    private void btn_saveClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveClientActionPerformed
            
            if(!client_name.getText().isEmpty() && 
                    !client_phone.getText().isEmpty() && 
                    !client_adress.getText().isEmpty() && 
                    !client_email.getText().isEmpty()){
            
                if(DBConnection.Connect()){
                    try{
                        Client client = new Client();
                        client.setF_name(client_name.getText());
                        client.setEmail(client_email.getText());
                        client.setTelephone(client_phone.getText());
                        client.setAdress(client_adress.getText());
                        if(DBConnection.AjouterClient(client)){System.out.println("Enregistrer avec succes");}else{System.out.println("Erreur d'enregistrement");}
                    }catch(Exception e){
                        System.out.println(e.getMessage());
                    
                    }
                }else{
                
                }
            }else{
            
                System.out.println("Les champs ne peuvent pas etre vide");
                MainScreen.infoBox("Les champs ne peuvent pas etre vide", "Erreur");
            }
    }//GEN-LAST:event_btn_saveClientActionPerformed

    private void client_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_client_nameActionPerformed

    private void client_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_client_phoneActionPerformed

    private void client_adressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client_adressActionPerformed

    }//GEN-LAST:event_client_adressActionPerformed

    private void client_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_client_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_annule;
    private javax.swing.JButton btn_saveClient;
    private javax.swing.JTextField client_adress;
    private javax.swing.JTextField client_email;
    private javax.swing.JTextField client_name;
    private javax.swing.JTextField client_phone;
    private javax.swing.JLabel jL_info1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jj;
    // End of variables declaration//GEN-END:variables
}

