/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Data.DBConnection;
import Data.Utils;
import Models.Produits;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Administrator
 */
public class AddProduct extends javax.swing.JFrame {

    /**
     * Creates new form AddProduct
     */
    public AddProduct() {
        initComponents();
        this.setLocationRelativeTo(null);
        Field_name.setText("");
        Field_constructor.setText("");
        
        DefaultComboBoxModel typeModel = new DefaultComboBoxModel();

        Utils u = new Utils();

        u.getType().forEach((_item) -> {
            typeModel.addElement(_item);
        });
        jCB_typeChooser.setModel(typeModel);
        
        Field_price.setText("");
        Field_quantite.setText("");
        jL_info1.setText("");
        setDefaultCloseOperation(AddProduct.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Field_name = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Field_constructor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Field_quantite = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Field_price = new javax.swing.JTextField();
        btn_enregister = new javax.swing.JButton();
        btn_annule = new javax.swing.JButton();
        jL_info1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jCB_typeChooser = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAlignmentX(200.0F);
        jPanel1.setAlignmentY(200.0F);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(41, 98, 255));

        jLabel1.setBackground(new java.awt.Color(41, 98, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ajout d'un nouveau produit");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 430, 50));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nom du produit");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 130, 30));

        Field_name.setBackground(new java.awt.Color(144, 202, 255));
        Field_name.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        Field_name.setForeground(new java.awt.Color(0, 0, 0));
        Field_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Field_name.setSelectionColor(new java.awt.Color(0, 0, 0));
        Field_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_nameActionPerformed(evt);
            }
        });
        jPanel1.add(Field_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 280, 30));

        jPanel3.setBackground(new java.awt.Color(41, 98, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 210));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Constructeur");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 130, 30));

        Field_constructor.setBackground(new java.awt.Color(144, 202, 255));
        Field_constructor.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        Field_constructor.setForeground(new java.awt.Color(0, 0, 0));
        Field_constructor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Field_constructor.setSelectionColor(new java.awt.Color(0, 0, 0));
        Field_constructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_constructorActionPerformed(evt);
            }
        });
        jPanel1.add(Field_constructor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 280, 30));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Type");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 130, 30));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Quantite");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 130, 30));

        Field_quantite.setBackground(new java.awt.Color(144, 202, 255));
        Field_quantite.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        Field_quantite.setForeground(new java.awt.Color(0, 0, 0));
        Field_quantite.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Field_quantite.setSelectionColor(new java.awt.Color(0, 0, 0));
        Field_quantite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_quantiteActionPerformed(evt);
            }
        });
        jPanel1.add(Field_quantite, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 280, 30));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Prix unitaire");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 130, 30));

        Field_price.setBackground(new java.awt.Color(144, 202, 255));
        Field_price.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        Field_price.setForeground(new java.awt.Color(0, 0, 0));
        Field_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Field_price.setSelectionColor(new java.awt.Color(0, 0, 0));
        Field_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_priceActionPerformed(evt);
            }
        });
        jPanel1.add(Field_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 280, 30));

        btn_enregister.setBackground(new java.awt.Color(13, 71, 161));
        btn_enregister.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        btn_enregister.setForeground(new java.awt.Color(255, 255, 255));
        btn_enregister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_save_white.png"))); // NOI18N
        btn_enregister.setText("Enregistrer");
        btn_enregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enregisterActionPerformed(evt);
            }
        });
        jPanel1.add(btn_enregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 180, 30));

        btn_annule.setBackground(new java.awt.Color(13, 71, 161));
        btn_annule.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        btn_annule.setForeground(new java.awt.Color(255, 255, 255));
        btn_annule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_cancel_white.png"))); // NOI18N
        btn_annule.setText("Annule");
        btn_annule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_annuleActionPerformed(evt);
            }
        });
        jPanel1.add(btn_annule, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 170, 30));

        jL_info1.setFont(new java.awt.Font("Footlight MT Light", 0, 24)); // NOI18N
        jL_info1.setForeground(new java.awt.Color(0, 76, 246));
        jL_info1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_info1.setText("jLabel7");
        jPanel1.add(jL_info1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 320, 20));

        jPanel4.setBackground(new java.awt.Color(41, 98, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, 210));

        jCB_typeChooser.setBackground(new java.awt.Color(255, 255, 255));
        jCB_typeChooser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCB_typeChooser.setForeground(new java.awt.Color(0, 0, 0));
        jCB_typeChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jCB_typeChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 280, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Field_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_nameActionPerformed

    private void Field_constructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_constructorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_constructorActionPerformed

    private void Field_quantiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_quantiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_quantiteActionPerformed

    private void Field_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_priceActionPerformed

    private void btn_enregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enregisterActionPerformed
        if (DBConnection.Connect()) {
            try {
                String nom = Field_name.getText();
                String constructor = Field_constructor.getText();
                float prix = Float.valueOf(Field_price.getText());
                int quantite = Integer.valueOf(Field_quantite.getText());
                String type = String.valueOf(jCB_typeChooser.getSelectedItem());
                Produits p = new Produits(nom, constructor, prix, quantite, type);
                if(DBConnection.AjouterProduit(p)) {
                    jL_info1.setText("Produit ajoute avec succes");
                    Field_name.setText("");
                    Field_constructor.setText("");
                    jCB_typeChooser.setSelectedIndex(0);
                    Field_price.setText("");
                    Field_quantite.setText("");
                    
                    
                } else {
                    jL_info1.setText("Erreur d'insertion");
                }
            } catch (NumberFormatException e) {
                jL_info1.setText("Verifier vos saisies");
                MainScreen.infoBox("Verifier vos saisies", "Erreur");
            }

        } else {
            jL_info1.setText("Erreur de connection");
            MainScreen.infoBox("Erreur de connection", "Info");
        }
    }//GEN-LAST:event_btn_enregisterActionPerformed

    private void btn_annuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_annuleActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_annuleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Field_constructor;
    private javax.swing.JTextField Field_name;
    private javax.swing.JTextField Field_price;
    private javax.swing.JTextField Field_quantite;
    private javax.swing.JButton btn_annule;
    private javax.swing.JButton btn_enregister;
    private javax.swing.JComboBox<String> jCB_typeChooser;
    private javax.swing.JLabel jL_info1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
